### PR TITLE
Metric to filter mapped.

### PR DESCRIPTION
**Pull request by Kuronoe-Ookami**
Hello.
I have an anime with a problem that its CombMask2 identifies very well, they are frames that look like the chroma is comb, delayed/advanced in relation to the scene (I'll post an example here): [dropbox](https://www.dropbox.com/scl/fo/cn8jl88gfsw7tbvad1qma/h?dl=0&rlkey=0uonrjwc0biirpedbty7pfnvm)

The solution I found is manual, changing the previous or next good frame for this bad one, however it is manual. 
I would like to know if there is a way to automate the writing of frames, such as in scene detection filters (SCDetect, for example) that use avspmod's "run analysis pass", in order to generate a .txt with the combed frame and make the manual process less painful.

Or if you know something that might help with this problem, I'm open to other options.
Anyway, thank you for your time 👍

### CODE REVIEW

**Comment by Asd-g** [comment]
Hi,

To write a file with frame numbers you can try something like:
```
video
CombMask2()
WriteFileIf("path_to_log", "AverageChromaU() > 1.0", "current_frame")
```

**Comment by Kuronoe-Ookami** [comment]
Hello.
Thank you very much, it worked perfectly.
This is one of the problems that annoys me the most with DVD, usually tied with frame blend. Even if I have to adjust these frames manually, it's much simpler to know where they are. I'll try to adjust this mode to frame blend, who knows if it does better when following srestore.
Thanks a lot for the help. 👍

**Comment by Kuronoe-Ookami** [comment]
Hi,
I would like to know if there would be a way to apply this theory that you helped me with to frameblend. I can't make a mask that takes these frames and it would be useful to have them in a .txt. 
I'm trying to make a model for that, something aimed at animes that break when converting NTSC > PAL and some old VHS. I'm not sure if the model supports this kind of thing, but it doesn't hurt to try.
I tried looking at the srestore code, but it's chaos. Then I tried with ExBlend, but the frames it delivers don't match.
Blend example: https://files.catbox.moe/7ddppd.mp4

Sorry for the many questions, I'm abusing your good will, but you're the only person I can ask about.

Any tips I would be grateful.

**Comment by Asd-g** [comment]
Hi,
I don't have a good solution on hand. You can ask/search in [doom9](https://forum.doom9.org/forumdisplay.php?f=33).

**Pull request closed without merging**
